# Default values for deepseek-coder helm chart.

# DeepSeek API settings
api:
  replicas: 1
  image:
    repository: ghcr.io/deepseek-ai/deepseek-coder
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      nvidia.com/gpu: 1
      memory: "32Gi"
      cpu: "8"
    requests:
      nvidia.com/gpu: 1
      memory: "16Gi"
      cpu: "4"
  nodeSelector:
    accelerator: nvidia-gpu
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  env:
    MODEL_SIZE: "base"
    LOG_LEVEL: "INFO"
    ENABLE_AUTH: "true"
    RATE_LIMIT: "100"

# Persistence settings
persistence:
  models:
    enabled: true
    storageClass: "nfs-client"
    size: 100Gi
  data:
    enabled: true
    storageClass: "nfs-client"
    size: 20Gi
  logs:
    enabled: true
    storageClass: "nfs-client"
    size: 10Gi

# Ingress settings
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    # Uncomment for SSL
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.deepseek.example.com
      paths:
        - path: /api
          pathType: Prefix
        - path: /health
          pathType: Exact
        - path: /docs
          pathType: Prefix
  tls: []
    # Uncomment for SSL
    # - secretName: deepseek-tls
    #   hosts:
    #     - api.deepseek.example.com

# Elasticsearch settings
elasticsearch:
  enabled: true
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 7.17.10
  service:
    type: ClusterIP
    port: 9200
  resources:
    limits:
      memory: 2Gi
      cpu: 1
    requests:
      memory: 1Gi
      cpu: 500m
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 20Gi
  env:
    ES_JAVA_OPTS: "-Xms1g -Xmx1g"

# Kibana settings
kibana:
  enabled: true
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 7.17.10
  service:
    type: ClusterIP
    port: 5601
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 200m
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 1Gi

# Monitoring settings
prometheus:
  enabled: true
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 10Gi

grafana:
  enabled: true
  adminPassword: "admin"
  persistence:
    enabled: true
    storageClass: "nfs-client"
    size: 2Gi
  dashboards:
    deepseek-coder:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "target": {
                  "limit": 100,
                  "matchAny": false,
                  "tags": [],
                  "type": "dashboard"
                },
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "panels": [
            {
              "datasource": "Prometheus",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 10,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "never",
                    "spanNulls": false
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "reqps"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "id": 2,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "targets": [
                {
                  "expr": "sum(rate(http_requests_total[1m]))",
                  "interval": "",
                  "legendFormat": "Requests per second",
                  "refId": "A"
                }
              ],
              "title": "API Request Rate",
              "type": "timeseries"
            },
            {
              "datasource": "Prometheus",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 10,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "never",
                    "spanNulls": false
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "percentunit"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 12,
                "y": 0
              },
              "id": 4,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "targets": [
                {
                  "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) / count by (instance) (node_cpu_seconds_total)",
                  "interval": "",
                  "legendFormat": "{{instance}}",
                  "refId": "A"
                }
              ],
              "title": "CPU Usage",
              "type": "timeseries"
            },
            {
              "datasource": "Prometheus",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 10,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "never",
                    "spanNulls": false
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "bytes"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 8
              },
              "id": 6,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "targets": [
                {
                  "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
                  "interval": "",
                  "legendFormat": "Memory Used",
                  "refId": "A"
                },
                {
                  "expr": "node_memory_MemTotal_bytes",
                  "interval": "",
                  "legendFormat": "Total Memory",
                  "refId": "B"
                }
              ],
              "title": "Memory Usage",
              "type": "timeseries"
            },
            {
              "datasource": "Prometheus",
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 10,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "never",
                    "spanNulls": false
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "percentunit"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 12,
                "y": 8
              },
              "id": 8,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "targets": [
                {
                  "expr": "DCGM_FI_DEV_GPU_UTIL / 100",
                  "interval": "",
                  "legendFormat": "GPU {{gpu}} Utilization",
                  "refId": "A"
                }
              ],
              "title": "GPU Utilization",
              "type": "timeseries"
            }
          ],
          "refresh": "10s",
          "schemaVersion": 30,
          "style": "dark",
          "tags": [],
          "title": "DeepSeek-Coder Dashboard",
          "uid": "deepseek-coder",
          "version": 1
        }
