version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: mcp-server
    environment:
      - CODEZAP_API_KEY=19d81b78fd79aafe3af0888a4e3de6bcdfe6f925675449431a2f9f24fafb92c2
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - mcp-network

  # Add any additional services here (e.g., database, cache)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - mcp-network

networks:
  mcp-network:
    driver: bridge
