name: fileboss-legal-intelligence
channels:
  - conda-forge
  - defaults
  - pytorch
  - huggingface
dependencies:
  # Core Python environment
  - python=3.11
  - pip
  - setuptools
  - wheel
  
  # Web framework and API
  - fastapi>=0.104.0
  - uvicorn[standard]>=0.24.0
  - gunicorn>=21.2.0
  - pydantic>=2.5.0
  - pydantic-settings>=2.1.0
  
  # Database and storage
  - sqlalchemy>=2.0.23
  - alembic>=1.13.0
  - asyncpg>=0.29.0
  - aiosqlite>=0.19.0
  - redis-py>=5.0.1
  
  # Legal document processing
  - pandas>=2.1.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - nltk>=3.8.0
  - spacy>=3.7.0
  - transformers>=4.35.0
  - torch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  
  # PDF and document analysis
  - pypdf2>=3.0.1
  - python-multipart>=0.0.6
  - python-docx>=1.1.0
  - openpyxl>=3.1.0
  - xlsxwriter>=3.1.0
  
  # Web scraping and API integration
  - requests>=2.31.0
  - aiohttp>=3.9.0
  - beautifulsoup4>=4.12.0
  - lxml>=4.9.0
  - httpx>=0.25.0
  
  # Security and encryption
  - cryptography>=41.0.0
  - passlib[bcrypt]>=1.7.4
  - python-jose[cryptography]>=3.3.0
  
  # Development and testing
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.0
  - pytest-cov>=4.1.0
  - black>=23.0.0
  - isort>=5.12.0
  - flake8>=6.0.0
  - mypy>=1.6.0
  
  # Monitoring and logging
  - prometheus-client>=0.19.0
  - structlog>=23.2.0
  - sentry-sdk>=1.38.0
  
  # E2B and sandbox integration
  - pip:
    - e2b>=0.15.0
    - mem0-ai>=0.1.0
    - supermemory-client>=1.0.0
    - jurisdiction-parser>=1.2.0
    - legal-entity-extractor>=0.8.0
    - courthouse-api>=2.1.0
    - federal-statute-parser>=1.5.0
    - case-timeline-builder>=0.9.0
    - evidence-classifier>=1.3.0
    - corruption-detector>=0.7.0
    - quantum-legal-analyzer>=2.0.0
    - memory-plugin-connector>=1.1.0
    - operator-code-bridge>=3.0.0
    - superluminal-matrix>=1.0.0
    - casebuilder-4000>=4.0.0
    - fileboss-core>=2.5.0
    - glacier-eq-integrator>=1.0.0
    - hawaiian-courts-api>=0.6.0
    - federal-escalation-engine>=1.2.0
    - kekoa-protection-protocols>=1.0.0