- choices:
    - index: 0
      message:
        role: assistant
        content: |
          {
            "message": "This is a test",
            "goal": "test goal",
            "title": "test title",
            "steps": [
              {
                "id": "1",
                "description": "test step"
              }
            ]
          }

- choices:
    - index: 0
      message:
        role: assistant
        content: null
        tool_calls:
          - type: function
            function:
              name: message_notify_user
              arguments: |
                {
                    "text": "test message tools."
                }

- choices:
    - index: 0
      message:
        role: assistant
        content: null
        tool_calls:
          - type: function
            function:
              name: file_write
              arguments: |
                {
                    "file": "/home/ubuntu/example.txt",
                    "content": "New content\nSecond line",
                    "append": false,
                    "leading_newline": true,
                    "trailing_newline": true
                }

- choices:
    - index: 0
      message:
        role: assistant
        content: null
        tool_calls:
          - type: function
            function:
              name: shell_exec
              arguments: |
                {
                    "id": "shell-1",
                    "exec_dir": "/home/ubuntu",
                    "command": "ls -la"
                }

- choices:
    - index: 0
      message:
        role: assistant
        content: null
        tool_calls:
          - type: function
            function:
              name: browser_navigate
              arguments: |
                {
                    "url": "https://www.example.com"
                }

- choices:
    - index: 0
      message:
        role: assistant
        content: |
          test end

- id: chatcmpl
  object: chat.completion
  model: gpt-4o
  choices:
    - index: 0
      message:
        role: assistant
        content: |
          {
            "steps": []
          }
      finish_reason: stop
