services:
  go-root:
    container_name: go-root
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    # env_file: ./.env  # Uncomment if .env file exists
    networks:
      - appnet
    ports:
      - "2342:2342"  # Exposed by Go app (photoprism)

  python-legal_brain:
    container_name: python-legal_brain
    build:
      context: ./Legal_brain
      dockerfile: Dockerfile
    restart: unless-stopped
    # env_file: ./Legal_brain/.env  # Uncomment if .env file exists
    networks:
      - appnet
    ports:
      - "8000:8000"  # Exposed by Legal_brain (Flask/FastAPI)
    depends_on:
      - go-root  # If Legal_brain depends on photoprism, adjust/remove as needed

  js-frontend:
    container_name: js-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    # env_file: ./frontend/.env  # Uncomment if .env file exists
    networks:
      - appnet
    ports:
      - "3000:3000"  # Exposed by frontend (Node server)
    depends_on:
      - go-root

  ts-electron-react-app:
    container_name: ts-electron-react-app
    build:
      context: ./electron-react-app
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    # env_file: ./electron-react-app/.env  # Uncomment if .env file exists
    networks:
      - appnet
    depends_on:
      - go-root

# Shared network for inter-service communication
networks:
  appnet:
    driver: bridge
