version: '3.8'

services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism_instance
    depends_on:
      - mariadb_photoprism
    ports:
      - "2342:2342" # Main PhotoPrism HTTP port
    environment:
      # --- Core Settings ---
      PHOTOPRISM_ADMIN_USER: "admin" 
      PHOTOPRISM_ADMIN_PASSWORD: "your_secure_photoprism_password" # !!! CHANGE THIS !!!
      PHOTOPRISM_SITE_URL: "http://localhost:2342/" 

      # --- Database Connection ---
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb_photoprism:3306" 
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism_user" 
      PHOTOPRISM_DATABASE_PASSWORD: "your_secure_db_user_password" # !!! CHANGE THIS !!!

      # --- Paths & Storage (INSIDE container) ---
      PHOTOPRISM_ORIGINALS_PATH: "/photoprism/originals"
      PHOTOPRISM_STORAGE_PATH: "/photoprism/storage" 
      PHOTOPRISM_IMPORT_PATH: "/photoprism/import"

      # --- Performance & Features ---
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "true" 
      PHOTOPRISM_DISABLE_TENSORFLOW: "false" 
      PHOTOPRISM_DETECT_NSFW: "true" # Or false if you prefer
      PHOTOPRISM_JPEG_QUALITY: 85 # Adjust as needed (75-95 is common)
      PHOTOPRISM_INIT: "tensorflow" 
      PHOTOPRISM_WORKERS: 4 # Adjust based on your CPU cores (e.g., if 8 cores, try 4-6)

    volumes:
      # --- Host paths (YOUR ACTUAL FOLDERS) ---
      - "D:\\PhotoPrism\\Originals:/photoprism/originals" 
      - "D:\\PhotoPrism\\Storage:/photoprism/storage"   
      - "D:\\PhotoPrism\\Import:/photoprism/import"     
    restart: unless-stopped

  mariadb_photoprism:
    image: mariadb:11 
    container_name: mariadb_photoprism_instance
    command: >
      --innodb-buffer-pool-size=512M
      --transaction-isolation=READ-COMMITTED
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max-connections=256 # Adjusted from 512, can be tuned
      --innodb-rollback-on-timeout=OFF
      --innodb-lock-wait-timeout=120
    ports: 
      - "3307:3306" # Host:Container, to avoid conflict if another MySQL/MariaDB runs on 3306
    volumes:
      - "D:\\PhotoPrism\\Database:/var/lib/mysql"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism" # Must match PHOTOPRISM_DATABASE_NAME
      MARIADB_USER: "photoprism_user" # Must match PHOTOPRISM_DATABASE_USER
      MARIADB_PASSWORD: "your_secure_db_user_password" # !!! CHANGE THIS !!! Must match PHOTOPRISM_DATABASE_PASSWORD
      MARIADB_ROOT_PASSWORD: "your_very_secure_root_db_password" # !!! CHANGE THIS !!!
    restart: unless-stopped

  whisper_service:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper_service_instance
    ports:
      - "9000:9000" 
    volumes:
      - "D:\\AIModels\\Whisper:/root/.cache/whisper" 
    environment:
      ASR_MODEL: "large-v3" # Or base, small, medium, large, large-v2
      # For CPU: ASR_ENGINE: faster-whisper (if image supports it and you want faster CPU)
      # For GPU: ASR_ENGINE: openai-whisper (default) or faster-whisper with device=cuda
    deploy: # For NVIDIA GPU acceleration
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]
    restart: unless-stopped

  legal_brain_service:
    build:
      context: ./Legal_brain # Path relative to this docker-compose file
      dockerfile: Dockerfile
    container_name: legal_brain_instance
    ports:
      - "8001:8000" # API for the legal brain (host:container)
    volumes:
      - "D:\\PhotoPrism\\Originals:/app/data/originals:ro" # Read-only access to originals
      - "D:\\PhotoPrism\\Import:/app/data/import"         # For files to be processed
      - "D:\\LegalBrain\\Data:/app/processed_data"       # For storing its own outputs/DB
      - "./Legal_brain:/app"                              # Mount code for easier development
    environment:
      PHOTOPRISM_API_URL: "http://photoprism_instance:2342/api/v1"
      PHOTOPRISM_ADMIN_USER: "admin" 
      PHOTOPRISM_ADMIN_PASSWORD: "your_secure_photoprism_password" # !!! CHANGE THIS !!! (must match photoprism service)
      WHISPER_API_URL: "http://whisper_service_instance:9000/asr"
      # OPENAI_API_KEY: "your_openai_key_if_needed" # If using OpenAI for other tasks
      FLASK_APP: "main.py" # Assuming your main Flask app is in main.py
      FLASK_DEBUG: "1" # Enable for development, disable for production
    depends_on:
      - photoprism
      - whisper_service
    restart: unless-stopped

# Removed 'volumes:' section for named volumes for now, using host binds primarily.
# Can be added back if preferred.
