apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deepseek-coder.fullname" . }}
  labels:
    {{- include "deepseek-coder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "deepseek-coder.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "deepseek-coder.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        {{- range $key, $value := .Values.api.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: PORT
          value: "8000"
        - name: ELASTICSEARCH_HOST
          value: {{ include "deepseek-coder.elasticsearch.fullname" . | quote }}
        - name: API_KEYS
          valueFrom:
            secretKeyRef:
              name: {{ include "deepseek-coder.fullname" . }}-secrets
              key: api-keys
        volumeMounts:
        - name: models
          mountPath: /app/models
        - name: data
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs
        resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: {{ include "deepseek-coder.fullname" . }}-models
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "deepseek-coder.fullname" . }}-data
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "deepseek-coder.fullname" . }}-logs
