class ConfigType:
    # Legacy LLM configurations
    LLM_API_KEY = 'LLM_API_KEY'
    LLM_BASE_URL = 'LLM_BASE_URL'
    LLM_MODEL = 'LLM_MODEL'
    LLM_EMBEDDING_MODEL = 'LLM_EMBEDDING_MODEL'
    LLM_DEPLOYMENT_NAME = 'LLM_DEPLOYMENT_NAME'
    LLM_API_VERSION = 'LLM_API_VERSION'
    LLM_NUM_RETRIES = 'LLM_NUM_RETRIES'
    LLM_COOLDOWN_TIME = 'LLM_COOLDOWN_TIME'
    
    # Multi-LLM Provider configurations
    LLM_ROUTING_ENABLED = 'LLM_ROUTING_ENABLED'
    LLM_AUTO_SELECTION = 'LLM_AUTO_SELECTION'
    LLM_FALLBACK_ENABLED = 'LLM_FALLBACK_ENABLED'
    LLM_COST_OPTIMIZATION = 'LLM_COST_OPTIMIZATION'
    LLM_PERFORMANCE_PREFERENCE = 'LLM_PERFORMANCE_PREFERENCE'
    
    # Provider-specific API keys
    OPENAI_API_KEY = 'OPENAI_API_KEY'
    ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY'
    DEEPSEEK_API_KEY = 'DEEPSEEK_API_KEY'
    OPENROUTER_API_KEY = 'OPENROUTER_API_KEY'
    COHERE_API_KEY = 'COHERE_API_KEY'
    TOGETHER_API_KEY = 'TOGETHER_API_KEY'
    NEBIUS_API_KEY = 'NEBIUS_API_KEY'
    
    # Workspace configurations
    WORKSPACE_BASE = 'WORKSPACE_BASE'
    WORKSPACE_MOUNT_PATH = 'WORKSPACE_MOUNT_PATH'
    WORKSPACE_MOUNT_REWRITE = 'WORKSPACE_MOUNT_REWRITE'
    
    # Sandbox configurations
    SANDBOX_CONTAINER_IMAGE = 'SANDBOX_CONTAINER_IMAGE'
    SANDBOX_TYPE = 'SANDBOX_TYPE'
    
    # Agent configurations
    RUN_AS_DEVIN = 'RUN_AS_DEVIN'
    AGENT = 'AGENT'
    MAX_ITERATIONS = 'MAX_ITERATIONS'
    MAX_CHARS = 'MAX_CHARS'
    
    # Network configurations
    USE_HOST_NETWORK = 'USE_HOST_NETWORK'
    SSH_HOSTNAME = 'SSH_HOSTNAME'
    
    # UI configurations
    DISABLE_COLOR = 'DISABLE_COLOR'
    
    # Supabase integration
    SUPABASE_URL = 'SUPABASE_URL'
    SUPABASE_ANON_KEY = 'SUPABASE_ANON_KEY'
    SUPABASE_SERVICE_ROLE_KEY = 'SUPABASE_SERVICE_ROLE_KEY'
    
    # Memory system configurations
    MEMORY_ENABLED = 'MEMORY_ENABLED'
    MEMORY_PROVIDER = 'MEMORY_PROVIDER'
    MAX_MEMORY_ITEMS = 'MAX_MEMORY_ITEMS'
    MEMORY_PERSISTENCE = 'MEMORY_PERSISTENCE'
    SESSION_MEMORY_ENABLED = 'SESSION_MEMORY_ENABLED'
    CROSS_SESSION_MEMORY = 'CROSS_SESSION_MEMORY'
    MEMORY_CONSOLIDATION_THRESHOLD = 'MEMORY_CONSOLIDATION_THRESHOLD'
    
    # Mem0 configurations
    MEM0_API_KEY = 'MEM0_API_KEY'
    MEM0_ORG_ID = 'MEM0_ORG_ID'
    MEM0_PROJECT_ID = 'MEM0_PROJECT_ID'
    
    # Memory storage configurations
    REDIS_URL = 'REDIS_URL'
    SQLITE_PATH = 'SQLITE_PATH'
    
    # Memory embedding configurations
    MEMORY_EMBEDDING_MODEL = 'MEMORY_EMBEDDING_MODEL'
    MEMORY_EMBEDDING_DIMENSION = 'MEMORY_EMBEDDING_DIMENSION'
    MEMORY_CHUNK_SIZE = 'MEMORY_CHUNK_SIZE'
    MEMORY_CHUNK_OVERLAP = 'MEMORY_CHUNK_OVERLAP'
    
    # Memory search configurations
    MEMORY_SIMILARITY_THRESHOLD = 'MEMORY_SIMILARITY_THRESHOLD'
    MEMORY_MAX_RESULTS = 'MEMORY_MAX_RESULTS'
    MEMORY_USE_HYBRID_SEARCH = 'MEMORY_USE_HYBRID_SEARCH'
    MEMORY_RERANK_RESULTS = 'MEMORY_RERANK_RESULTS'
    
    # Memory plugin configurations
    MEMORY_AUTO_SUMMARIZATION = 'MEMORY_AUTO_SUMMARIZATION'
    MEMORY_CONTEXTUAL_RECALL = 'MEMORY_CONTEXTUAL_RECALL'
    MEMORY_LEARNING_ADAPTATION = 'MEMORY_LEARNING_ADAPTATION'
    MEMORY_CONSOLIDATION = 'MEMORY_CONSOLIDATION'
