[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "deepseek-coder"
version = "1.0.0"
description = "DeepSeek-Coder: Advanced AI code assistant trained on 2T tokens of code and documentation"
authors = ["DeepSeek AI Team <service@deepseek.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/deepseek-ai/deepseek-coder"
repository = "https://github.com/deepseek-ai/deepseek-coder"
documentation = "https://github.com/deepseek-ai/deepseek-coder"
keywords = ["ai", "code", "generation", "completion", "nlp", "transformer"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
torch = ">=2.0.0"
transformers = ">=4.30.0"
numpy = ">=1.23.0"
pandas = ">=1.5.0"
scipy = ">=1.10.0"
scikit-learn = ">=1.2.0"
fastapi = ">=0.95.0"
uvicorn = ">=0.22.0"
pydantic = ">=1.10.7"

[tool.poetry.dev-dependencies]
pytest = ">=7.3.1"
black = ">=23.3.0"
isort = ">=5.12.0"
mypy = ">=1.3.0"
pre-commit = ">=3.3.2"

[tool.poetry.extras]
gpu = ["accelerate>=0.20.0", "bitsandbytes>=0.40.0"]
api = ["fastapi>=0.95.0", "uvicorn>=0.22.0"]
legal = ["beautifulsoup4>=4.12.0", "playwright>=1.33.0", "selenium>=4.9.0"]
dev = ["pytest>=7.3.1", "black>=23.3.0", "isort>=5.12.0", "mypy>=1.3.0"]

[tool.black]
line-length = 100
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = false
check_untyped_defs = true
ignore_missing_imports = true
exclude = [
    '^venv$',
    '^build$',
    '^dist$',
    '^docs$',
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
addopts = "--verbose --color=yes"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "gpu: marks tests that require GPU (deselect with '-m \"not gpu\"')",
]
