name: Dependency Review

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/dependency-review-action@v4
